// ============================================================
// VEREDILLAS FM — Achievement System (50+ Badges)
// ============================================================

export interface AchievementProgress {
  current: number;
  max: number;
  unit: string;        // e.g. 'min', 'h', 'episodios', 'días', 'comentarios'
  formatValue?: (n: number) => string; // optional display formatter
}

export interface Achievement {
  id: string;
  name: string;
  description: string;
  icon: string;         // Emoji icon
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'mythic';
  category: 'escucha' | 'social' | 'exploracion' | 'coleccion' | 'especial' | 'fidelidad' | 'madrugador' | 'coleccionista' | 'maraton' | 'desafio';
  check: (stats: AchievementStats) => boolean;
  /** If defined, the UI will render a progress bar for this achievement. */
  progress?: (stats: AchievementStats) => AchievementProgress;
  secret?: boolean;
  points: number;
}

export interface AchievementStats {
  listeningTime: number;           // seconds
  favoritesCount: number;
  playbackHistoryCount: number;    // total episodes ever played
  completedEpisodesCount: number;  // episodes listened to ≥ 80%
  consecutiveEpisodes: number;     // max episodes listened back-to-back (same session)
  commentsCount: number;           // total comments posted
  likedClipsCount: number;
  newsletterSubscribed: boolean;
  // Derived
  daysSinceJoin: number;
  favoritedSeasonsCount: number;   // distinct seasons favorited
  totalSeasonsCount: number;
  loginStreakDays: number;         // current consecutive login days
  maxStreakDays: number;           // all-time record
  hasProfilePicture: boolean;
  hasBio: boolean;
  joinedYear: number;
  peakListeningHour: number;       // 0-23, for night-owl badge
  episodesListenedThisWeek: number;
  chatMessagesCount: number;
  unlockedCardsCount: number;      // cromos
  totalCardsCount: number;         // total available cromos
  differentGuestsListenedCount: number;
  bioLength: number;
  totalQuizzesCount: number;       // total quizzes completed
  referralsCount: number;          // total users referred
  /** Sum of points from already-unlocked achievements — computed server-side before evaluating meta-achievements. */
  totalPoints: number;
}

// Rarity colours for UI display
export const RARITY_COLORS: Record<Achievement['rarity'], string> = {
  common:    '#9ca3af',
  uncommon:  '#4ade80',
  rare:      '#60a5fa',
  epic:      '#a855f7',
  legendary: '#f59e0b',
  mythic:    '#ef4444',
};

export const RARITY_LABELS: Record<Achievement['rarity'], string> = {
  common:    'Común',
  uncommon:  'Poco común',
  rare:      'Raro',
  epic:      'Épico',
  legendary: 'Legendario',
  mythic:    'Mítico',
};

export const CATEGORY_LABELS: Record<Achievement['category'], string> = {
  escucha:    '🎧 Escucha',
  social:     '💬 Social',
  exploracion:'🗺️ Exploración',
  coleccion:  '❤️ Colección',
  especial:   '✨ Especial',
  fidelidad:  '🔥 Fidelidad',
  madrugador: '🌙 Madrugador',
  coleccionista: '🃏 Coleccionista',
  maraton:    '🏃 Maratonista',
  desafio:    '🧠 Desafío',
};

// ──────────────────────────────────────────────────────────────
// ACHIEVEMENT DEFINITIONS (50+)
// ──────────────────────────────────────────────────────────────
export const ACHIEVEMENTS: Achievement[] = [

  // ─── ESCUCHA ────────────────────────────────────────────────
  {
    id: 'primer_minuto',
    name: 'Primer Minuto',
    description: 'Escucha tu primer episodio por al menos 1 minuto.',
    icon: '▶️',
    rarity: 'common',
    category: 'escucha',
    points: 10,
    check: s => s.listeningTime >= 60,
    progress: s => ({ current: Math.min(s.listeningTime, 60), max: 60, unit: 's' }),
  },
  {
    id: 'primer_fan',
    name: 'Primer Fan',
    description: 'Completa tu primer episodio entero.',
    icon: '🌱',
    rarity: 'common',
    category: 'escucha',
    points: 15,
    check: s => s.completedEpisodesCount >= 1,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 1), max: 1, unit: 'episodio' }),
  },
  {
    id: 'media_hora',
    name: 'Media Hora de Podcast',
    description: 'Acumula 30 minutos de escucha total.',
    icon: '⏱️',
    rarity: 'common',
    category: 'escucha',
    points: 20,
    check: s => s.listeningTime >= 1800,
    progress: s => ({ current: Math.min(Math.floor(s.listeningTime / 60), 30), max: 30, unit: 'min' }),
  },
  {
    id: 'oyente_casual',
    name: 'Oyente Casual',
    description: 'Acumula 1 hora de escucha total.',
    icon: '🎧',
    rarity: 'common',
    category: 'escucha',
    points: 30,
    check: s => s.listeningTime >= 3600,
    progress: s => ({ current: Math.min(Math.floor(s.listeningTime / 60), 60), max: 60, unit: 'min' }),
  },
  {
    id: 'tres_horas',
    name: 'Adicto a la Escucha',
    description: 'Acumula 3 horas de escucha total.',
    icon: '🔊',
    rarity: 'uncommon',
    category: 'escucha',
    points: 60,
    check: s => s.listeningTime >= 10800,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 3), max: 3, unit: 'h' }),
  },
  {
    id: 'cinco_episodios',
    name: 'Cinco de Cinco',
    description: 'Completa 5 episodios al 100%.',
    icon: '5️⃣',
    rarity: 'uncommon',
    category: 'escucha',
    points: 55,
    check: s => s.completedEpisodesCount >= 5,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 5), max: 5, unit: 'episodios' }),
  },
  {
    id: 'diez_horas',
    name: 'Década de Horas',
    description: 'Acumula 10 horas de escucha total.',
    icon: '🔟',
    rarity: 'rare',
    category: 'escucha',
    points: 100,
    check: s => s.listeningTime >= 36000,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 10), max: 10, unit: 'h' }),
  },
  {
    id: 'veinte_episodios',
    name: 'Enganchado',
    description: 'Completa 20 episodios al 100%.',
    icon: '🔗',
    rarity: 'rare',
    category: 'escucha',
    points: 120,
    check: s => s.completedEpisodesCount >= 20,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 20), max: 20, unit: 'episodios' }),
  },
  {
    id: 'veinticinco_horas',
    name: 'Un Día Entero',
    description: 'Acumula 25 horas de escucha total.',
    icon: '🌅',
    rarity: 'epic',
    category: 'escucha',
    points: 200,
    check: s => s.listeningTime >= 90000,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 25), max: 25, unit: 'h' }),
  },
  {
    id: 'cincuenta_episodios',
    name: 'Cincuentón',
    description: 'Completa 50 episodios al 100%.',
    icon: '🏆',
    rarity: 'epic',
    category: 'escucha',
    points: 250,
    check: s => s.completedEpisodesCount >= 50,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 50), max: 50, unit: 'episodios' }),
  },
  {
    id: 'cien_horas',
    name: 'Centurión del Podcast',
    description: 'Acumula 100 horas de escucha total.',
    icon: '💯',
    rarity: 'legendary',
    category: 'escucha',
    points: 500,
    check: s => s.listeningTime >= 360000,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 100), max: 100, unit: 'h' }),
  },

  // ─── FIDELIDAD ──────────────────────────────────────────────
  {
    id: 'primera_semana',
    name: 'Primera Semana',
    description: 'Lleva 7 días siendo miembro de Veredillas FM.',
    icon: '📅',
    rarity: 'common',
    category: 'fidelidad',
    points: 20,
    check: s => s.daysSinceJoin >= 7,
    progress: s => ({ current: Math.min(s.daysSinceJoin, 7), max: 7, unit: 'días' }),
  },
  {
    id: 'primer_mes',
    name: 'Miembro del Mes',
    description: 'Lleva 30 días siendo miembro de Veredillas FM.',
    icon: '🗓️',
    rarity: 'uncommon',
    category: 'fidelidad',
    points: 50,
    check: s => s.daysSinceJoin >= 30,
    progress: s => ({ current: Math.min(s.daysSinceJoin, 30), max: 30, unit: 'días' }),
  },
  {
    id: 'tres_meses',
    name: 'Fan Trimestral',
    description: 'Lleva 90 días siendo miembro de Veredillas FM.',
    icon: '🌿',
    rarity: 'rare',
    category: 'fidelidad',
    points: 100,
    check: s => s.daysSinceJoin >= 90,
    progress: s => ({ current: Math.min(s.daysSinceJoin, 90), max: 90, unit: 'días' }),
  },
  {
    id: 'seis_meses',
    name: 'Semestre de Podcast',
    description: 'Lleva 180 días siendo miembro de Veredillas FM.',
    icon: '🌳',
    rarity: 'epic',
    category: 'fidelidad',
    points: 200,
    check: s => s.daysSinceJoin >= 180,
    progress: s => ({ current: Math.min(s.daysSinceJoin, 180), max: 180, unit: 'días' }),
  },
  {
    id: 'un_ano',
    name: 'Fan Anual',
    description: 'Lleva 365 días siendo miembro de Veredillas FM.',
    icon: '🎂',
    rarity: 'legendary',
    category: 'fidelidad',
    points: 400,
    check: s => s.daysSinceJoin >= 365,
    progress: s => ({ current: Math.min(s.daysSinceJoin, 365), max: 365, unit: 'días' }),
  },
  {
    id: 'racha_semanal',
    name: 'Racha Semanal',
    description: 'Conéctate durante 7 días seguidos.',
    icon: '🔥',
    rarity: 'uncommon',
    category: 'fidelidad',
    points: 60,
    check: s => s.loginStreakDays >= 7,
    progress: s => ({ current: Math.min(s.loginStreakDays, 7), max: 7, unit: 'días seguidos' }),
  },
  {
    id: 'racha_mensual',
    name: 'Imparable Diarios',
    description: 'Conéctate durante 30 días seguidos.',
    icon: '💎',
    rarity: 'epic',
    category: 'fidelidad',
    points: 250,
    check: s => s.loginStreakDays >= 30,
    progress: s => ({ current: Math.min(s.loginStreakDays, 30), max: 30, unit: 'días seguidos' }),
  },
  {
    id: 'racha_oro',
    name: 'Racha de Oro',
    description: 'Consigue tu mejor marca personal de 50 días seguidos.',
    icon: '🏆',
    rarity: 'legendary',
    category: 'fidelidad',
    points: 1000,
    check: s => s.maxStreakDays >= 50,
    progress: s => ({ current: Math.min(s.maxStreakDays, 50), max: 50, unit: 'días (récord)' }),
    secret: true,
  },
  {
    id: 'og_member',
    name: 'Miembro OG',
    description: 'Te uniste a Veredillas FM en 2026.',
    icon: '👑',
    rarity: 'legendary',
    category: 'fidelidad',
    points: 300,
    check: s => s.joinedYear <= 2026,
    secret: true,
  },

  // ─── SOCIAL ─────────────────────────────────────────────────
  {
    id: 'primer_comentario',
    name: 'La Voz del Oyente',
    description: 'Publica tu primer comentario en un episodio.',
    icon: '💬',
    rarity: 'common',
    category: 'social',
    points: 15,
    check: s => s.commentsCount >= 1,
    progress: s => ({ current: Math.min(s.commentsCount, 1), max: 1, unit: 'comentario' }),
  },
  {
    id: 'comentarista_activo',
    name: 'Comentarista Activo',
    description: 'Publica 10 comentarios en episodios.',
    icon: '🗣️',
    rarity: 'uncommon',
    category: 'social',
    points: 70,
    check: s => s.commentsCount >= 10,
    progress: s => ({ current: Math.min(s.commentsCount, 10), max: 10, unit: 'comentarios' }),
  },
  {
    id: 'comentarista_pro',
    name: 'Comentarista Pro',
    description: 'Publica 25 comentarios en episodios.',
    icon: '📝',
    rarity: 'rare',
    category: 'social',
    points: 120,
    check: s => s.commentsCount >= 25,
    progress: s => ({ current: Math.min(s.commentsCount, 25), max: 25, unit: 'comentarios' }),
  },
  {
    id: 'comentarista_leyenda',
    name: 'Cronista del Podcast',
    description: 'Publica 50 comentarios en episodios.',
    icon: '📰',
    rarity: 'epic',
    category: 'social',
    points: 300,
    check: s => s.commentsCount >= 50,
    progress: s => ({ current: Math.min(s.commentsCount, 50), max: 50, unit: 'comentarios' }),
  },
  {
    id: 'primer_chat',
    name: 'Hola Mundo',
    description: 'Envía tu primer mensaje en el chat en vivo.',
    icon: '👋',
    rarity: 'common',
    category: 'social',
    points: 10,
    check: s => s.chatMessagesCount >= 1,
  },
  {
    id: 'cien_mensajes_chat',
    name: 'Chateador Empedernido',
    description: 'Envía 100 mensajes en el chat en vivo.',
    icon: '🌊',
    rarity: 'rare',
    category: 'social',
    points: 110,
    check: s => s.chatMessagesCount >= 100,
    progress: s => ({ current: Math.min(s.chatMessagesCount, 100), max: 100, unit: 'mensajes' }),
  },
  {
    id: 'newsletter',
    name: '¡Suscrito!',
    description: 'Te suscribiste a la newsletter de Veredillas FM.',
    icon: '📧',
    rarity: 'common',
    category: 'social',
    points: 20,
    check: s => s.newsletterSubscribed,
  },

  // ─── COLECCIÓN ──────────────────────────────────────────────
  {
    id: 'primer_favorito',
    name: 'Guardado para Después',
    description: 'Añade tu primer episodio a favoritos.',
    icon: '⭐',
    rarity: 'common',
    category: 'coleccion',
    points: 10,
    check: s => s.favoritesCount >= 1,
  },
  {
    id: 'diez_favoritos',
    name: 'Coleccionista',
    description: 'Ten 10 episodios en favoritos al mismo tiempo.',
    icon: '🗃️',
    rarity: 'uncommon',
    category: 'coleccion',
    points: 50,
    check: s => s.favoritesCount >= 10,
    progress: s => ({ current: Math.min(s.favoritesCount, 10), max: 10, unit: 'favoritos' }),
  },
  {
    id: 'veinte_favoritos',
    name: 'Gran Colección',
    description: 'Ten 20 episodios en favoritos.',
    icon: '🏛️',
    rarity: 'rare',
    category: 'coleccion',
    points: 90,
    check: s => s.favoritesCount >= 20,
    progress: s => ({ current: Math.min(s.favoritesCount, 20), max: 20, unit: 'favoritos' }),
  },
  {
    id: 'primer_clip',
    name: 'Clip Lover',
    description: 'Da Me Gusta a tu primer clip.',
    icon: '🎞️',
    rarity: 'common',
    category: 'coleccion',
    points: 10,
    check: s => s.likedClipsCount >= 1,
  },
  {
    id: 'diez_clips',
    name: 'Cinéfilo del Podcast',
    description: 'Da Me Gusta a 10 clips.',
    icon: '🎬',
    rarity: 'uncommon',
    category: 'coleccion',
    points: 45,
    check: s => s.likedClipsCount >= 10,
    progress: s => ({ current: Math.min(s.likedClipsCount, 10), max: 10, unit: 'clips' }),
  },

  // ─── EXPLORACIÓN ────────────────────────────────────────────
  {
    id: 'perfil_completo',
    name: 'Cara y Cruz',
    description: 'Completa tu perfil con foto y biografía.',
    icon: '🪪',
    rarity: 'common',
    category: 'exploracion',
    points: 25,
    check: s => s.hasProfilePicture && s.hasBio,
  },
  {
    id: 'tres_secciones',
    name: 'Explorador Curioso',
    description: 'Visita al menos 3 secciones diferentes del sitio.',
    icon: '🗺️',
    rarity: 'common',
    category: 'exploracion',
    points: 15,
    check: s => s.playbackHistoryCount >= 3,
  },

  // ─── MADRUGADOR / NOCTÁMBULO ────────────────────────────────
  {
    id: 'noctambulo',
    name: 'Noctámbulo',
    description: 'Escucha un episodio entre las 00:00 y las 04:00.',
    icon: '🌙',
    rarity: 'uncommon',
    category: 'madrugador',
    points: 40,
    check: s => s.peakListeningHour >= 0 && s.peakListeningHour <= 4,
    secret: true,
  },
  {
    id: 'madrugador',
    name: 'Madrugador',
    description: 'Escucha un episodio entre las 05:00 y las 07:00.',
    icon: '🌅',
    rarity: 'uncommon',
    category: 'madrugador',
    points: 35,
    check: s => s.peakListeningHour >= 5 && s.peakListeningHour <= 7,
    secret: true,
  },

  // ─── ESPECIAL ───────────────────────────────────────────────
  {
    id: 'konami',
    name: 'Jugador Retro',
    description: 'Descubriste el código secreto Konami.',
    icon: '🕹️',
    rarity: 'rare',
    category: 'especial',
    points: 75,
    check: _s => false, // Unlocked manually via frontend event
    secret: true,
  },

  {
    id: 'estrella',
    name: 'Estrella del Podcast',
    description: 'Consigue 500 puntos de logros en total.',
    icon: '⭐',
    rarity: 'epic',
    category: 'especial',
    points: 0, // meta-achievement, no extra points to avoid infinite loops
    check: s => s.totalPoints >= 500,
    progress: s => ({ current: Math.min(s.totalPoints, 500), max: 500, unit: 'pts' }),
  },
  {
    id: 'vip',
    name: 'VIP Veredillas',
    description: 'Alcanza el nivel máximo y completa 30 episodios.',
    icon: '💜',
    rarity: 'legendary',
    category: 'especial',
    points: 500,
    check: s => s.listeningTime >= 18000 && s.completedEpisodesCount >= 30,
    secret: true,
  },
  {
    id: 'todo_favorito',
    name: 'Me Gusta Todo',
    description: 'Ten más de 30 episodios en favoritos.',
    icon: '💝',
    rarity: 'epic',
    category: 'coleccion',
    points: 180,
    check: s => s.favoritesCount >= 30,
    progress: s => ({ current: Math.min(s.favoritesCount, 30), max: 30, unit: 'favoritos' }),
  },
  {
    id: 'sesenta_horas',
    name: 'Maestro del Podcast',
    description: 'Acumula 60 horas de escucha total.',
    icon: '🎓',
    rarity: 'epic',
    category: 'escucha',
    points: 350,
    check: s => s.listeningTime >= 216000,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 60), max: 60, unit: 'h' }),
  },
  {
    id: 'fan_numero_uno',
    name: 'Fan Número 1',
    description: 'Consigue todos los logros de la categoría Escucha.',
    icon: '🥇',
    rarity: 'legendary',
    category: 'especial',
    points: 700,
    check: _s => false, // Derived from other achievements
    secret: true,
  },
  {
    id: 'cuarenta_episodios',
    name: 'La Cuarentena',
    description: 'Completa 40 episodios al 100%.',
    icon: '4️⃣',
    rarity: 'epic',
    category: 'escucha',
    points: 220,
    check: s => s.completedEpisodesCount >= 40,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 40), max: 40, unit: 'episodios' }),
  },
  {
    id: 'doce_meses',
    name: 'Año de Veredillas',
    description: 'Lleva 365 días registrado. ¡Feliz aniversario!',
    icon: '🎊',
    rarity: 'legendary',
    category: 'fidelidad',
    points: 500,
    check: s => s.daysSinceJoin >= 365,
    secret: true,
  },

  // ─── NUEVOS LOGROS (ADICIONALES 50) ──────────────────────────

  // ESCUCHA (CONTINUACIÓN)
  {
    id: 'ciento_cincuenta_horas',
    name: 'Bibliotecario Auditivo',
    description: 'Acumula 150 horas de escucha total.',
    icon: '📚',
    rarity: 'legendary',
    category: 'escucha',
    points: 600,
    check: s => s.listeningTime >= 540000,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 150), max: 150, unit: 'h' }),
  },
  {
    id: 'doscientas_horas',
    name: 'Sabio de Veredillas',
    description: 'Acumula 200 horas de escucha total.',
    icon: '🧘',
    rarity: 'legendary',
    category: 'escucha',
    points: 800,
    check: s => s.listeningTime >= 720000,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 200), max: 200, unit: 'h' }),
  },
  {
    id: 'setenta_y_cinco_episodios',
    name: 'Platino de Escucha',
    description: 'Completa 75 episodios al 100%.',
    icon: '💿',
    rarity: 'epic',
    category: 'escucha',
    points: 350,
    check: s => s.completedEpisodesCount >= 75,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 75), max: 75, unit: 'episodios' }),
  },
  {
    id: 'cien_episodios',
    name: 'Leyenda del Reproductor',
    description: 'Completa 100 episodios al 100%.',
    icon: '🏺',
    rarity: 'legendary',
    category: 'escucha',
    points: 1000,
    check: s => s.completedEpisodesCount >= 100,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 100), max: 100, unit: 'episodios' }),
  },
  {
    id: 'mil_minutos',
    name: 'Kilominuto',
    description: 'Escucha un total de 1,000 minutos.',
    icon: '⌚',
    rarity: 'uncommon',
    category: 'escucha',
    points: 75,
    check: s => s.listeningTime >= 60000,
    progress: s => ({ current: Math.min(Math.floor(s.listeningTime / 60), 1000), max: 1000, unit: 'min' }),
  },

  // SOCIAL (CONTINUACIÓN)
  {
    id: 'cien_comentarios',
    name: 'Voz Plateada',
    description: 'Publica 100 comentarios en la plataforma.',
    icon: '🥈',
    rarity: 'epic',
    category: 'social',
    points: 400,
    check: s => s.commentsCount >= 100,
    progress: s => ({ current: Math.min(s.commentsCount, 100), max: 100, unit: 'comentarios' }),
  },
  {
    id: 'doscientos_mensajes_chat',
    name: 'Chatter de Élite',
    description: 'Supera los 200 mensajes en el chat en vivo.',
    icon: '⚡',
    rarity: 'rare',
    category: 'social',
    points: 180,
    check: s => s.chatMessagesCount >= 200,
    progress: s => ({ current: Math.min(s.chatMessagesCount, 200), max: 200, unit: 'mensajes' }),
  },
  {
    id: 'quinientos_mensajes_chat',
    name: 'Señor del Chat',
    description: 'Envía 500 mensajes en el chat. ¡No hay quien te calle!',
    icon: '📢',
    rarity: 'epic',
    category: 'social',
    points: 350,
    check: s => s.chatMessagesCount >= 500,
    progress: s => ({ current: Math.min(s.chatMessagesCount, 500), max: 500, unit: 'mensajes' }),
  },
  {
    id: 'mil_mensajes_chat',
    name: 'Bot Humano',
    description: 'Alcanza la cifra legendaria de 1,000 mensajes en el chat.',
    icon: '🤖',
    rarity: 'legendary',
    category: 'social',
    points: 750,
    check: s => s.chatMessagesCount >= 1000,
    progress: s => ({ current: Math.min(s.chatMessagesCount, 1000), max: 1000, unit: 'mensajes' }),
    secret: true,
  },
  {
    id: 'cincuenta_clips',
    name: 'Maestro del Clip',
    description: 'Da Me Gusta a 50 clips diferentes.',
    icon: '🎬',
    rarity: 'rare',
    category: 'coleccion',
    points: 200,
    check: s => s.likedClipsCount >= 50,
    progress: s => ({ current: Math.min(s.likedClipsCount, 50), max: 50, unit: 'clips' }),
  },
  {
    id: 'social_butterfly',
    name: 'Mariposa Social',
    description: 'Comenta, chatea, suscríbete a la newsletter y dale a like a un clip.',
    icon: '🦋',
    rarity: 'rare',
    category: 'social',
    points: 150,
    check: s => s.commentsCount >= 1 && s.chatMessagesCount >= 1 && s.newsletterSubscribed && s.likedClipsCount >= 1,
    secret: true,
  },

  // FIDELIDAD (CONTINUACIÓN)
  {
    id: 'dos_anos',
    name: 'Veterano de Veredillas',
    description: 'Lleva 2 años (730 días) siendo parte de la comunidad.',
    icon: '🎖️',
    rarity: 'legendary',
    category: 'fidelidad',
    points: 800,
    check: s => s.daysSinceJoin >= 730,
    progress: s => ({ current: Math.min(s.daysSinceJoin, 730), max: 730, unit: 'días' }),
  },
  {
    id: 'racha_cien',
    name: 'Fuego Eterno',
    description: 'Mantén una racha de conexión de 100 días.',
    icon: '🔥',
    rarity: 'legendary',
    category: 'fidelidad',
    points: 1500,
    check: s => s.loginStreakDays >= 100,
    progress: s => ({ current: Math.min(s.loginStreakDays, 100), max: 100, unit: 'días' }),
  },
  {
    id: 'regreso_triunfal',
    name: 'Regreso Triunfal',
    description: 'Vuelve a conectar después de tener una racha máxima de al menos 10 días.',
    icon: '♻️',
    rarity: 'uncommon',
    category: 'fidelidad',
    points: 50,
    check: s => s.maxStreakDays >= 10 && s.loginStreakDays === 1,
    secret: true,
  },

  // COLECCIONISTA (NUEVA CATEGORÍA)
  {
    id: 'primer_cromo',
    name: '¡Tengo uno!',
    description: 'Desbloquea tu primer cromo de invitado.',
    icon: '🃏',
    rarity: 'common',
    category: 'coleccionista',
    points: 20,
    check: s => s.unlockedCardsCount >= 1,
  },
  {
    id: 'cinco_cromos',
    name: 'Fan de los Invitados',
    description: 'Colecciona 5 cromos de invitados diferentes.',
    icon: '✋',
    rarity: 'uncommon',
    category: 'coleccionista',
    points: 80,
    check: s => s.unlockedCardsCount >= 5,
    progress: s => ({ current: Math.min(s.unlockedCardsCount, 5), max: 5, unit: 'cromos' }),
  },
  {
    id: 'diez_cromos',
    name: 'Caza Talentos',
    description: 'Colecciona 10 cromos de invitados.',
    icon: '🎯',
    rarity: 'rare',
    category: 'coleccionista',
    points: 150,
    check: s => s.unlockedCardsCount >= 10,
    progress: s => ({ current: Math.min(s.unlockedCardsCount, 10), max: 10, unit: 'cromos' }),
  },
  {
    id: 'veinte_cromos',
    name: 'Museo de Voces',
    description: 'Colecciona 20 cromos de invitados.',
    icon: '🏛️',
    rarity: 'epic',
    category: 'coleccionista',
    points: 300,
    check: s => s.unlockedCardsCount >= 20,
    progress: s => ({ current: Math.min(s.unlockedCardsCount, 20), max: 20, unit: 'cromos' }),
  },
  {
    id: 'coleccionista_plata',
    name: 'Coleccionista de Plata',
    description: 'Desbloquea el 50% de todos los cromos disponibles.',
    icon: '🥈',
    rarity: 'epic',
    category: 'coleccionista',
    points: 400,
    check: s => (s.unlockedCardsCount / s.totalCardsCount) >= 0.5 && s.totalCardsCount > 0,
    progress: s => ({ current: s.unlockedCardsCount, max: Math.ceil(s.totalCardsCount / 2), unit: 'cromos' }),
  },
  {
    id: 'album_completo',
    name: 'Completista Magnífico',
    description: 'Consigue todos los cromos del álbum.',
    icon: '👑',
    rarity: 'legendary',
    category: 'coleccionista',
    points: 1000,
    check: s => s.unlockedCardsCount >= s.totalCardsCount && s.totalCardsCount > 0,
    progress: s => ({ current: s.unlockedCardsCount, max: s.totalCardsCount, unit: 'cromos' }),
  },

  // MARATON (NUEVA CATEGORÍA)
  {
    id: 'maraton_diez',
    name: 'Maratón Semanal',
    description: 'Escucha 10 episodios en una sola semana.',
    icon: '🏃',
    rarity: 'rare',
    category: 'maraton',
    points: 120,
    check: s => s.episodesListenedThisWeek >= 10,
    progress: s => ({ current: Math.min(s.episodesListenedThisWeek, 10), max: 10, unit: 'episodios' }),
  },
  {
    id: 'maraton_veinte',
    name: 'Siete Días sin Sueño',
    description: 'Escucha 20 episodios en una sola semana.',
    icon: '🌀',
    rarity: 'epic',
    category: 'maraton',
    points: 300,
    check: s => s.episodesListenedThisWeek >= 20,
    progress: s => ({ current: Math.min(s.episodesListenedThisWeek, 20), max: 20, unit: 'episodios' }),
  },
  {
    id: 'maraton_cincuenta',
    name: 'El Corredor de Fondo',
    description: 'Escucha 50 episodios en una sola semana.',
    icon: '🏁',
    rarity: 'legendary',
    category: 'maraton',
    points: 800,
    check: s => s.episodesListenedThisWeek >= 50,
    progress: s => ({ current: Math.min(s.episodesListenedThisWeek, 50), max: 50, unit: 'episodios' }),
    secret: true,
  },

  // EXPLORACIÓN (CONTINUACIÓN)

  {
    id: 'diez_secciones',
    name: 'Turista Digital',
    description: 'Has explorado profundamente el sitio (10+ episodios diferentes).',
    icon: '🧭',
    rarity: 'rare',
    category: 'exploracion',
    points: 100,
    check: s => s.playbackHistoryCount >= 10,
  },
  {
    id: 'variedad_invitados',
    name: 'Oído Abierto',
    description: 'Escucha entrevistas de 10 invitados diferentes.',
    icon: '🎭',
    rarity: 'rare',
    category: 'exploracion',
    points: 150,
    check: s => s.differentGuestsListenedCount >= 10,
    progress: s => ({ current: Math.min(s.differentGuestsListenedCount, 10), max: 10, unit: 'invitados' }),
  },

  // ESPECIAL (CONTINUACIÓN)
  {
    id: 'punto_mil',
    name: 'Millonario de Puntos',
    description: 'Consigue 1,000 puntos de logros.',
    icon: '💰',
    rarity: 'rare',
    category: 'especial',
    points: 100,
    check: s => s.totalPoints >= 1000,
    progress: s => ({ current: Math.min(s.totalPoints, 1000), max: 1000, unit: 'pts' }),
  },
  {
    id: 'punto_dosmil',
    name: 'Doble Millonario',
    description: 'Consigue 2,000 puntos de logros.',
    icon: '💎',
    rarity: 'epic',
    category: 'especial',
    points: 200,
    check: s => s.totalPoints >= 2000,
    progress: s => ({ current: Math.min(s.totalPoints, 2000), max: 2000, unit: 'pts' }),
  },
  {
    id: 'punto_cincomil',
    name: 'Deidad del Ranking',
    description: 'Consigue 5,000 puntos de logros. ¿Cómo es posible?',
    icon: '🎇',
    rarity: 'legendary',
    category: 'especial',
    points: 500,
    check: s => s.totalPoints >= 5000,
    progress: s => ({ current: Math.min(s.totalPoints, 5000), max: 5000, unit: 'pts' }),
    secret: true,
  },
  {
    id: 'completista_comun',
    name: 'Base Sólida',
    description: 'Consigue todos los logros de rareza Común.',
    icon: '🧱',
    rarity: 'rare',
    category: 'especial',
    points: 200,
    check: _s => false, // Meta
    secret: true,
  },
  {
    id: 'maestro_del_konami_pro',
    name: 'Dedo Veloz',
    description: 'Descubriste el Código Konami y has enviado 100 mensajes.',
    icon: '⌨️',
    rarity: 'epic',
    category: 'especial',
    points: 250,
    check: s => s.chatMessagesCount >= 100, // Partial logic, meta check elsewhere
    secret: true,
  },

  // MÁS LOGROS PARA LLEGAR A 50
  {
    id: 'fan_madrugada',
    name: 'Vampiro del Podcast',
    description: 'Tu hora pico de escucha es entre las 3 AM y las 4 AM.',
    icon: '🧛',
    rarity: 'rare',
    category: 'madrugador',
    points: 100,
    check: s => s.peakListeningHour >= 3 && s.peakListeningHour <= 4,
    secret: true,
  },
  {
    id: 'fan_amanecer',
    name: 'Canto del Gallo',
    description: 'Tu hora pico de escucha es exactamente a las 5 AM.',
    icon: '🐓',
    rarity: 'rare',
    category: 'madrugador',
    points: 120,
    check: s => s.peakListeningHour === 5,
    secret: true,
  },
  {
    id: 'coleccionista_bronce_meta',
    name: 'Aprendiz de Museo',
    description: 'Desbloquea el 25% de los cromos.',
    icon: '🥉',
    rarity: 'uncommon',
    category: 'coleccionista',
    points: 100,
    check: s => (s.unlockedCardsCount / s.totalCardsCount) >= 0.25 && s.totalCardsCount > 0,
  },
  {
    id: 'favoritos_cincuenta',
    name: 'Curador de Arte',
    description: 'Añade 50 episodios a tus favoritos.',
    icon: '🖼️',
    rarity: 'epic',
    category: 'coleccion',
    points: 300,
    check: s => s.favoritesCount >= 50,
    progress: s => ({ current: Math.min(s.favoritesCount, 50), max: 50, unit: 'favoritos' }),
  },
  {
    id: 'mega_fan_cien',
    name: 'Archivo Viviente',
    description: 'Añade 100 episodios a tus favoritos.',
    icon: '⛩️',
    rarity: 'legendary',
    category: 'coleccion',
    points: 600,
    check: s => s.favoritesCount >= 100,
    progress: s => ({ current: Math.min(s.favoritesCount, 100), max: 100, unit: 'favoritos' }),
  },
  {
    id: 'escucha_aniversario',
    name: 'Un año escuchando',
    description: 'Has completado al menos 50 episodios y llevas un año registrado.',
    icon: '🎉',
    rarity: 'epic',
    category: 'fidelidad',
    points: 450,
    check: s => s.completedEpisodesCount >= 50 && s.daysSinceJoin >= 365,
    secret: true,
  },
  {
    id: 'social_king',
    name: 'Rey de la Comunidad',
    description: 'Suma 50 comentarios y 500 mensajes de chat.',
    icon: '👑',
    rarity: 'epic',
    category: 'social',
    points: 500,
    check: s => s.commentsCount >= 50 && s.chatMessagesCount >= 500,
  },
  {
    id: 'explorador_total',
    name: 'Conozco cada rincón',
    description: 'Completa tu perfil, suscríbete y escucha 20 episodios.',
    icon: '🛰️',
    rarity: 'rare',
    category: 'exploracion',
    points: 200,
    check: s => s.hasProfilePicture && s.hasBio && s.newsletterSubscribed && s.playbackHistoryCount >= 20,
  },
  {
    id: 'maraton_extrema_cien',
    name: 'No tengo vida social',
    description: 'Escucha 100 episodios en una sola semana.',
    icon: '💀',
    rarity: 'legendary',
    category: 'maraton',
    points: 2000,
    check: s => s.episodesListenedThisWeek >= 100,
    secret: true,
  },
  {
    id: 'lealtad_quinientos',
    name: 'Lealtad Inquebrantable',
    description: 'Lleva 500 días en Veredillas FM.',
    icon: '💍',
    rarity: 'legendary',
    category: 'fidelidad',
    points: 1200,
    check: s => s.daysSinceJoin >= 500,
    progress: s => ({ current: Math.min(s.daysSinceJoin, 500), max: 500, unit: 'días' }),
  },
  {
    id: 'influenciador_junior',
    name: 'Influenciador Junior',
    description: 'Consigue que tus comentarios y likes en clips sumen 50 interacciones.',
    icon: '🤳',
    rarity: 'uncommon',
    category: 'social',
    points: 100,
    check: s => (s.commentsCount + s.likedClipsCount) >= 50,
  },
  {
    id: 'fan_seasons_all',
    name: 'Cronista de Temporadas',
    description: 'Escucha al menos un episodio de cada temporada disponible.',
    icon: '📂',
    rarity: 'rare',
    category: 'escucha',
    points: 200,
    check: s => s.playbackHistoryCount >= s.totalSeasonsCount && s.totalSeasonsCount > 1,
  },
  {
    id: 'perfeccionista_v2',
    name: 'Perfeccionista Supremo',
    description: 'Completa 200 episodios al 100%.',
    icon: '🔥',
    rarity: 'legendary',
    category: 'escucha',
    points: 2500,
    check: s => s.completedEpisodesCount >= 200,
    progress: s => ({ current: Math.min(s.completedEpisodesCount, 200), max: 200, unit: 'episodios' }),
  },
  {
    id: 'punto_diezmil',
    name: 'Leyenda Viviente de VFM',
    description: 'Alcanza los 10,000 puntos de logros.',
    icon: '🌌',
    rarity: 'legendary',
    category: 'especial',
    points: 1000,
    check: s => s.totalPoints >= 10000,
    secret: true,
  },
  {
    id: 'oyente_nocturno_leyenda',
    name: 'Pesadilla en Veredillas',
    description: 'Escucha 50 episodios en horario nocturno (00-04h).',
    icon: '👻',
    rarity: 'epic',
    category: 'madrugador',
    points: 400,
    check: s => s.peakListeningHour >= 0 && s.peakListeningHour <= 4 && s.completedEpisodesCount >= 50,
    secret: true,
  },
  {
    id: 'primer_paso_cromo',
    name: 'Iniciando el Álbum',
    description: 'Completa tu primer cromo de la Temporada 1.',
    icon: '🎟️',
    rarity: 'common',
    category: 'coleccionista',
    points: 30,
    check: s => s.unlockedCardsCount >= 1,
  },
  {
    id: 'maestro_de_la_voz',
    name: 'Sabio de la Escucha',
    description: 'Acumula 300 horas de escucha.',
    icon: '🧠',
    rarity: 'legendary',
    category: 'escucha',
    points: 1500,
    check: s => s.listeningTime >= 1080000,
    progress: s => ({ current: Math.min(parseFloat((s.listeningTime / 3600).toFixed(1)), 300), max: 300, unit: 'h' }),
  },
  {
    id: 'el_elegido',
    name: 'El Elegido',
    description: 'Consigue el logro VIP y además ten 500 mensajes de chat.',
    icon: '✨',
    rarity: 'legendary',
    category: 'especial',
    points: 1000,
    check: s => s.listeningTime >= 18000 && s.completedEpisodesCount >= 30 && s.chatMessagesCount >= 500,
    secret: true,
  },
  // ─── REFERIDOS (SOCIAL) ──────────────────────────────────
  {
    id: 'referido_uno',
    name: 'El Boca a Boca',
    description: 'Invita a tu primer amigo a Veredillas FM.',
    icon: '🤝',
    rarity: 'common',
    category: 'social',
    points: 30,
    check: s => s.referralsCount >= 1,
    progress: s => ({ current: Math.min(s.referralsCount, 1), max: 1, unit: 'amigo' }),
  },
  {
    id: 'referidos_dos',
    name: 'Doble Impacto',
    description: 'Invita a 2 amigos a la plataforma.',
    icon: '👯',
    rarity: 'uncommon',
    category: 'social',
    points: 60,
    check: s => s.referralsCount >= 2,
    progress: s => ({ current: Math.min(s.referralsCount, 2), max: 2, unit: 'amigos' }),
  },
  {
    id: 'referidos_cinco',
    name: 'El Relaciones Públicas',
    description: 'Invita a 5 amigos a Veredillas FM.',
    icon: '📢',
    rarity: 'rare',
    category: 'social',
    points: 150,
    check: s => s.referralsCount >= 5,
    progress: s => ({ current: Math.min(s.referralsCount, 5), max: 5, unit: 'amigos' }),
  },
  {
    id: 'referidos_diez',
    name: 'El Embajador',
    description: 'Invita a 10 amigos a la comunidad. ¡Gracias por compartir!',
    icon: '🌍',
    rarity: 'epic',
    category: 'social',
    points: 300,
    check: s => s.referralsCount >= 10,
    progress: s => ({ current: Math.min(s.referralsCount, 10), max: 10, unit: 'amigos' }),
  },

  // ─── DESAFÍOS (QUIZZES) ──────────────────────────────────
  {
    id: 'primer_quiz',
    name: 'Primer Desafío',
    description: 'Completa tu primer cuestionario de episodio.',
    icon: '🧠',
    rarity: 'common',
    category: 'desafio',
    points: 20,
    check: s => s.totalQuizzesCount >= 1,
    progress: s => ({ current: Math.min(s.totalQuizzesCount, 1), max: 1, unit: 'quiz' }),
  },
  {
    id: 'estudiante_aplicado',
    name: 'Estudiante Aplicado',
    description: 'Completa 5 cuestionarios de episodios.',
    icon: '📝',
    rarity: 'uncommon',
    category: 'desafio',
    points: 50,
    check: s => s.totalQuizzesCount >= 5,
    progress: s => ({ current: Math.min(s.totalQuizzesCount, 5), max: 5, unit: 'quizzes' }),
  },
  {
    id: 'maestro_examen',
    name: 'Maestro del Examen',
    description: 'Completa 10 cuestionarios de episodios.',
    icon: '🎓',
    rarity: 'rare',
    category: 'desafio',
    points: 120,
    check: s => s.totalQuizzesCount >= 10,
    progress: s => ({ current: Math.min(s.totalQuizzesCount, 10), max: 10, unit: 'quizzes' }),
  },
  {
    id: 'enciclopedia_viviente',
    name: 'Enciclopedia Viviente',
    description: 'Completa 25 cuestionarios de episodios.',
    icon: '📖',
    rarity: 'epic',
    category: 'desafio',
    points: 300,
    check: s => s.totalQuizzesCount >= 25,
    progress: s => ({ current: Math.min(s.totalQuizzesCount, 25), max: 25, unit: 'quizzes' }),
  },
  {
    id: 'leyenda_veredillas',
    name: 'Leyenda de Veredillas',
    description: 'Completa 50 cuestionarios de episodios. ¡Dominio absoluto!',
    icon: '👑',
    rarity: 'legendary',
    category: 'desafio',
    points: 600,
    check: s => s.totalQuizzesCount >= 50,
    progress: s => ({ current: Math.min(s.totalQuizzesCount, 50), max: 50, unit: 'quizzes' }),
  },
];

// ──────────────────────────────────────────────────────────────
// HELPER UTILITIES
// ──────────────────────────────────────────────────────────────

/** Returns all achievements that the stats qualify for. */
export function computeUnlockedAchievements(stats: AchievementStats): string[] {
  return ACHIEVEMENTS.filter(a => a.check(stats)).map(a => a.id);
}

/** Get a single achievement definition by id. */
export function getAchievementById(id: string): Achievement | undefined {
  return ACHIEVEMENTS.find(a => a.id === id);
}

/** Sort achievements by rarity weight for display. */
export const RARITY_ORDER: Record<Achievement['rarity'], number> = {
  mythic:    0,
  legendary: 1,
  epic:      2,
  rare:      3,
  uncommon:  4,
  common:    5,
};

export function sortByRarity(list: Achievement[]): Achievement[] {
  return [...list].sort((a, b) => RARITY_ORDER[a.rarity] - RARITY_ORDER[b.rarity]);
}
