
export const welcomePhrases = [
    "¡Hola, {userName}! Estás escuchando Veredillas efe-eme en directo. Relájate y disfruta.",
    "Bienvenido a la radio, {userName}. Sube el volumen que la mejor música suena ahora.",
    "Sintonizando la frecuencia oficial de Veredillas efe-eme. ¡Dale caña, {userName}!",
    "¿Qué pasa, {userName}? Qué bueno tenerte por aquí. Estás en tu casa, estás en Veredillas FM.",
    "¡Ey, {userName}! Gracias por elegirnos. Prepárate para una sesión épica.",
    "Hola, {userName}. La mejor compañía para tu día está aquí, en Veredillas efe-eme.",
    "¡Qué alegría saludarte, {userName}! La música no para y nosotros tampoco.",
    "Bienvenido a bordo, {userName}. Ajusta tus altavoces que empezamos fuerte.",
    "¡Hola, hola! {userName}, ya estás conectado a la señal que mueve tu mundo.",
    "¿Listo para lo que viene, {userName}? Veredillas FM ya está en tus oídos.",
    "¡Buenas vibras, {userName}! Estás en el lugar correcto, en el momento adecuado.",
    "Hola, {userName}. Aquí tienes el mejor sonido de la red. ¡Disfrútalo!",
    "¡Qué tal, {userName}! La cabina está lista y tú también. ¡Dale al play!",
    "Bienvenido a la comunidad de Veredillas efe-eme, {userName}. ¡Siéntete libre!",
    "¡Ese {userName}! Ya estamos en el aire. No te muevas de ahí.",
    "Hola, {userName}. Tu banda sonora favorita acaba de empezar.",
    "¡Saludos, {userName}! Sintonizas la radio que nunca duerme.",
    "¿Cómo va todo, {userName}? Súbete al carro de Veredillas FM.",
    "¡Hola de nuevo, {userName}! La música es el alma y aquí tenemos mucha.",
    "Bienvenido, {userName}. Prepárate para un viaje sonoro inolvidable.",
    "¡Qué pasa, familia! Y en especial tú, {userName}. ¡Dale caña!",
    "Hola, {userName}. Pon el volumen al máximo, que esto promete.",
    "¡Ey, {userName}! Gracias por estar al otro lado. ¡Veredillas FM a tope!",
    "Bienvenido a la frecuencia de la felicidad, {userName}.",
    "¡Hola, {userName}! Deja que la música hable por ti hoy.",
    "¿Qué tal, {userName}? Conéctate, relájate y goza con nosotros.",
    "¡Saludos cordiales, {userName}! Estás escuchando calidad pura.",
    "Hola, {userName}. Veredillas FM te da la bienvenida oficial.",
    "¡Ey, {userName}! Dale ritmo a tu vida con nuestra señal en vivo.",
    "Bienvenido al sonido del mañana, hoy, en Veredillas FM, {userName}.",
    "¡Atención, {userName}! Estás entrando en zona de alta fidelidad.",
    "Hola, {userName}. ¿Preparado para subir el nivel de tu día?",
    "¡Qué onda, {userName}! La radio está que arde y tú eres parte de esto.",
    "Bienvenido, {userName}. Sintoniza tu mente con Veredillas efe-eme.",
    "¡Hola, {userName}! Ponle banda sonora a tus sueños aquí mismo.",
    "¿Qué tal va ese día, {userName}? Nosotros le ponemos el ritmo.",
    "¡Ey, {userName}! Quédate con nosotros, que la cosa se pone interesante.",
    "Hola, {userName}. La señal es clara: es hora de disfrutar.",
    "¡Saludos, {userName}! Veredillas FM, tu conexión directa con el éxito.",
    "Bienvenido a tu oasis musical, {userName}. ¡Ponte cómodo!",
    "¡Hola, {userName}! La mejor música no se busca, se sintoniza aquí.",
    "¿Listo para vibrar, {userName}? Veredillas efe-eme ya está contigo.",
    "¡Ey, {userName}! Déjate llevar por el sonido que nos une.",
    "Hola, {userName}. Hoy es un buen día para escuchar temazos.",
    "¡Bienvenido a la antena, {userName}! Tu dosis diaria de energía.",
    "¡Hola, {userName}! Gracias por darnos un hueco en tu mundo.",
    "¿Qué pasa, {userName}? Súbele que esto es Veredillas efe-eme.",
    "¡Saludos, {userName}! Estás en la cresta de la ola musical.",
    "Hola, {userName}. Disfruta de la radio sin filtros ni fronteras.",
    "¡Bienvenido, {userName}! Veredillas FM: música, amigos y mucho más."
];

export const transitionPhrases = [
    "¡Qué locura de tema nos acaba de regalar {currentArtist}! Pero ojo, {userName}, porque no bajamos el ritmo. Prepárate porque ahora entra {nextArtist} con {nextTitle}. ¡Súbele a Veredillas efe eme!",
    "Ahí lo tenías, {currentTitle} sonando duro. Y si creías que eso era todo, espera a escuchar lo que sigue. En exclusiva, {nextTitle} de {nextArtist}. Solo aquí, en tu radio favorita.",
    "¡Familia! La vibra está por las nubes después de escuchar a {currentArtist}. Vamos a mantener la energía a tope porque se viene {nextArtist} con {nextTitle}. ¡No te lo pierdas!",
    "Tremendo palo este de {currentTitle}. Y la cosa se pone aún mejor. Acomódate bien, {userName}, porque llega {nextArtist} directo a tus oídos con {nextTitle}.",
    "Estás sintonizando Veredillas efe eme. Despedimos a {currentArtist} y le damos la bienvenida a {nextArtist} con su temazo, {nextTitle}. ¡Disfrútalo!",
    "¡Uf, qué buena rolita de {currentArtist}! Seguimos activos en cabina y ahora toca el turno de {nextTitle}, lo nuevo de {nextArtist}. Sube ese volumen.",
    "La música no para en Veredillas efe eme. Después de este exitazo, nos vamos con {nextArtist} y su increíble tema, {nextTitle}. ¡Vámonos!",
    "Si te gustó lo de {currentArtist}, lo que viene te va a encantar. Directamente para ti, {userName}, suena {nextTitle} de {nextArtist}. ¡Pura calidad!",
    "¡Seguimos rompiendo la antena! Atrás quedó {currentTitle} y nos metemos de lleno con el sonido único de {nextArtist} cantando {nextTitle}.",
    "¡Wow, qué energía! Así suena {currentArtist} en Veredillas efe eme. Y ahora, prepárate para cantar a todo pulmón con {nextArtist} y su éxito {nextTitle}.",
    "¡Vaya, vaya! Terminamos de gozar con {currentArtist}, pero aquí en Veredillas efe eme la fiesta apenas comienza. Atento a lo que suena ahora: {nextTitle} de {nextArtist}.",
    "Qué buena onda nos dejó {currentArtist}. Si estás escuchando esto, {userName}, ponte cómodo porque el siguiente hit es {nextTitle}, interpretado por {nextArtist}.",
    "¡Se encendió la cabina! Acabamos de vibrar con {currentTitle}, y para seguir con el mismo mood, te dejamos con {nextArtist} y su temón, {nextTitle}.",
    "Nadie pone la música como Veredillas efe eme. Despídete de {currentArtist}, porque ya está en la pista {nextArtist} con {nextTitle}. ¡A romperla!",
    "Pausa tus problemas, {userName}, porque acaba de terminar {currentTitle} y se viene un bombazo: nada menos que {nextArtist} trayéndonos {nextTitle}.",
    "Acabamos de escuchar a {currentArtist}, dejando la vara altísima. Pero no te preocupes, que ahora viene {nextArtist} con {nextTitle} para seguir dándolo todo.",
    "El flow no se negocia aquí en Veredillas efe eme. Se va {currentTitle} pero entra {nextTitle}, de la mano de {nextArtist}. Sube, sube el volumen.",
    "¡Menudo viaje musical con {currentArtist}! Agárrate fuerte porque la siguiente pista es brutal. Con ustedes, {nextArtist} y {nextTitle}.",
    "Si estabas bailando con {currentTitle}, no pares todavía. Llegó el momento de {nextArtist} con {nextTitle}. ¡Directo a tu cerebro!",
    "¡Atención, {userName}! Ya pasó {currentArtist}, y lo que te tengo preparado ahora es oro puro. Escucha bien: esto es {nextTitle} de {nextArtist} en Veredillas efe eme.",
    "¡Qué flow se gasta {currentArtist}! Pero prepárate porque lo que viene ahora con {nextArtist} es de otro planeta. Aquí suena {nextTitle}.",
    "Acabamos de soltar a la bestia con {currentArtist}. Y para seguir en la cima, entra {nextArtist} pisando fuerte con {nextTitle}.",
    "¡Impresionante {currentTitle}! {userName}, no te desconectes porque {nextArtist} viene a romper los esquemas con su nuevo hit {nextTitle}.",
    "La antena está ardiendo tras escuchar a {currentArtist}. Vamos a refrescar con el sonido fresco de {nextArtist} y su tema {nextTitle}.",
    "¡Eso fue épico! Gracias {currentArtist}. Ahora, {userName}, abre paso a la leyenda: {nextArtist} nos trae {nextTitle}.",
    "Sintonizas Veredillas FM, la casa de los éxitos. Despedimos a {currentArtist} para recibir con honores a {nextArtist} y {nextTitle}.",
    "¡Vaya ritmo! {currentArtist} nos ha dejado con ganas de más, y {nextArtist} tiene la respuesta exacta con {nextTitle}.",
    "No hay tregua en Veredillas efe eme. Terminamos con {currentArtist} y saltamos directamente a lo nuevo de {nextArtist}: {nextTitle}.",
    "¡Menudo temazo de {currentArtist}! Pero lo que viene ahora con {nextArtist} y {nextTitle} es simplemente ilegal. ¡Escucha!",
    "La cabina vibra todavía con {currentArtist}. Para mantener la intensidad, aquí tienes a {nextArtist} dándolo todo en {nextTitle}.",
    "¡Familia, atención! Si {currentArtist} te gustó, espera a que {nextArtist} empiece a sonar con {nextTitle}. ¡Pura magia!",
    "¡Qué grande {currentArtist}! Seguimos en modo fiesta y ahora es el turno de {nextArtist} con su temazo {nextTitle}.",
    "¡Increíble! Así suena {currentTitle} en directo. Pero no bajamos la guardia, porque {nextArtist} ya está aquí con {nextTitle}.",
    "¿Quieres más? Pues toma nota: {nextArtist} entra en escena con {nextTitle} justo después de este hit de {currentArtist}.",
    "¡Brutal {currentArtist}! {userName}, súbele un punto más al volumen porque {nextArtist} llega con {nextTitle}.",
    "La esencia de Veredillas FM está en mezclas como esta. De {currentArtist} pasamos a {nextArtist} con {nextTitle}. ¡Disfruta!",
    "¡Qué clase tiene {currentArtist}! Pero la elegancia sigue con {nextArtist} y su propuesta para hoy: {nextTitle}.",
    "¡Vaya subidón con {currentArtist}! Para que no decaiga la cosa, {nextArtist} nos regala {nextTitle}. ¡Dale!",
    "Despedimos a lo grande a {currentArtist}. Y sin resuello, nos metemos de lleno en {nextTitle} de {nextArtist}.",
    "¡Ese es el sonido! {currentArtist} dejando el listón muy alto para {nextArtist}, que viene a superarlo con {nextTitle}.",
    "¡Locura total en la radio! Acabamos de vibrar con {currentArtist} y ya estamos listos para recibir a {nextArtist} y su {nextTitle}.",
    "¡Pura dinamita {currentArtist}! Pero cuidado con la mecha que trae {nextArtist} en su tema {nextTitle}.",
    "¡Qué bien suena {currentArtist}! Pero prepárate para lo que {nextArtist} ha preparado para ti: se llama {nextTitle}.",
    "La radio que tú quieres te trae a {currentArtist} y ahora, en exclusiva, a {nextArtist} con {nextTitle}.",
    "¡Vaya viaje nos ha dado {currentArtist}! La siguiente parada es {nextArtist} con {nextTitle}. ¡No te bajes!",
    "¡Imparables! Así somos en Veredillas FM. Tras {currentArtist}, llega el torbellino {nextArtist} con {nextTitle}.",
    "¡Menuda joya de {currentArtist}! Pero el tesoro sigue con {nextArtist} y su gran éxito {nextTitle}.",
    "¡Ritmo puro con {currentArtist}! Pero agárrate, {userName}, que {nextArtist} viene con curvas en {nextTitle}.",
    "¡Qué pegadizo lo de {currentArtist}! Pues espera a escuchar el estribillo de {nextArtist} en {nextTitle}. ¡Espectacular!",
    "Veredillas FM no para de sorprenderte. De la mano de {currentArtist} saltamos a {nextArtist} y su {nextTitle}.",
    "¡Vaya energía nos deja {currentArtist}! Ideal para recibir con los brazos abiertos a {nextArtist} y su {nextTitle}.",
    "¡Qué sonido más limpio el de {currentArtist}! La pureza sigue con {nextArtist} en su tema {nextTitle}.",
    "¡Atención a la antena! Acabamos de escuchar a {currentArtist} y ya tenemos en rampa de salida a {nextArtist} con {nextTitle}.",
    "¡Espectacular {currentTitle}! Pero {userName}, lo que ha hecho {nextArtist} en {nextTitle} es para quitarse el sombrero.",
    "La mezcla perfecta: {currentArtist} y ahora {nextArtist} con {nextTitle}. Solo en Veredillas efe eme.",
    "¡Menudo hit de {currentArtist}! Pero el futuro suena a {nextArtist} y su canción {nextTitle}. ¡Atento!",
    "¡Qué potencia la de {currentArtist}! Para seguir con la fuerza, aquí está {nextArtist} con {nextTitle}.",
    "¡Vaya clásico de {currentArtist}! Renovamos la energía con {nextArtist} y su moderno {nextTitle}.",
    "¡Insuperable {currentArtist}! O eso creíamos, hasta que escuchamos lo que {nextArtist} trae en {nextTitle}.",
    "¡Qué bien nos lo pasamos con {currentArtist}! La diversión continúa con {nextArtist} y {nextTitle}.",
    "¡Menudo groove el de {currentArtist}! La onda sigue fluyendo con {nextArtist} en su tema {nextTitle}.",
    "¡Fantástico {currentArtist}! {userName}, prepárate para el impacto de {nextArtist} con {nextTitle}.",
    "¡Qué voz la de {currentArtist}! Pues espera a escuchar los matices de {nextArtist} en {nextTitle}.",
    "¡Inolvidable {currentTitle}! Pero vamos a crear nuevos recuerdos con {nextArtist} y {nextTitle}.",
    "¡Vaya ritmo nos ha metido en el cuerpo {currentArtist}! {nextArtist} viene a mantenerlo vivo con {nextTitle}.",
    "¡Qué elegancia {currentArtist}! La distinción continúa en Veredillas FM con {nextArtist} y {nextTitle}.",
    "¡Menudo pepinazo de {currentArtist}! Pero la bomba atómica la trae {nextArtist} con {nextTitle}. ¡PUM!",
    "¡Qué maravilla {currentArtist}! La magia no se acaba, ahora entra {nextArtist} con {nextTitle}.",
    "¡Vaya exhibición de {currentArtist}! El espectáculo sigue con {nextArtist} y su {nextTitle}.",
    "¡Qué temazo, por Dios! Gracias {currentArtist}. Ahora, {userName}, a disfrutar con {nextArtist} y {nextTitle}.",
    "¡Simplemente brutal {currentArtist}! Pero no paramos, porque {nextArtist} viene con todo en {nextTitle}.",
    "¡Veredillas FM al poder! Tras {currentArtist}, recibimos con un aplauso digital a {nextArtist} y {nextTitle}.",
    "¡Qué flow, qué estilo el de {currentArtist}! La tendencia sigue con {nextArtist} en su tema {nextTitle}.",
    "¡Menudo descubrimiento {currentArtist}! Pero los éxitos conocidos también tienen su sitio: aquí está {nextArtist} con {nextTitle}.",
    "¡Vaya subida nos ha pegado {currentArtist}! Para mantenerte en las nubes, {nextArtist} nos trae {nextTitle}.",
    "¡Qué fuerza la de {currentTitle}! Pero la garra de {nextArtist} en {nextTitle} te va a sorprender.",
    "¡No hay quien nos pare! De {currentArtist} a {nextArtist} con {nextTitle}. ¡Veredillas FM a tope!",
    "¡Qué bien entra {currentArtist} a estas horas! Y mejor va a entrar {nextArtist} con {nextTitle}. ¡Verás!",
    "¡Menuda pieza de colección de {currentArtist}! Pero lo nuevo de {nextArtist} también es oro puro: {nextTitle}.",
    "¡Vaya energía positiva de {currentArtist}! Transmitimos ese buen rollo ahora a {nextArtist} y su {nextTitle}.",
    "¡Qué talento el de {currentArtist}! El genio continúa en la antena con {nextArtist} y {nextTitle}.",
    "¡Incredible vibe with {currentArtist}! Pero volvemos con {nextArtist} y su temazo {nextTitle}. ¡No te lo pierdas!",
    "¡Vaya temazo de {currentArtist}! Pero ojo que {nextArtist} viene pisando fuerte con {nextTitle}. ¡Dale!",
    "¡Qué ritmo de {currentArtist}! Seguimos activos en Veredillas FM con {nextArtist} y su canción {nextTitle}.",
    "¡Eso fue increíble! Gracias {currentArtist}. Ahora, {userName}, prepárate para {nextArtist} con {nextTitle}.",
    "¡Qué barbaridad {currentArtist}! {userName}, prepárate porque lo que sigue con {nextArtist} va a ser leyenda. Suena {nextTitle}.",
    "Terminamos el viaje con {currentArtist}. Siguiente destino: el universo musical de {nextArtist} y su {nextTitle}.",
    "¡Vaya hit! {currentArtist} nos deja con ganas de más, y {nextArtist} no decepciona con {nextTitle}.",
    "Sintonizas Veredillas FM. Despedimos a {currentArtist} y damos paso a la artillería pesada de {nextArtist} en {nextTitle}.",
    "¡Qué flow se gasta {currentArtist}! Pero la temperatura va a subir aún más con {nextArtist} y {nextTitle}.",
    "¡Simplemente espectacular! Gracias {currentArtist}. Ahora, {userName}, abre bien los oídos para {nextArtist} y {nextTitle}.",
    "No bajamos el ritmo. Tras {currentArtist}, entra en escena {nextArtist} con su flamante {nextTitle}.",
    "¡Qué nivel el de {currentArtist}! {nextArtist} tiene el reto de superarlo y viene con todo en {nextTitle}.",
    "La antena vibra con {currentTitle}. Vamos a duplicar la apuesta con {nextArtist} y {nextTitle}. ¡Dale!",
    "¡Vaya pepinazo! {currentArtist} ha puesto la cabina a mil. {nextArtist} viene a mantener el fuego con {nextTitle}.",
    "¡Qué clase tiene {currentArtist}! Pero la elegancia sigue fluyendo con {nextArtist} y {nextTitle}.",
    "¡Menudo subidón! {currentArtist} nos ha volado la cabeza. {nextArtist} nos trae de vuelta con {nextTitle}.",
    "¡Imparables! Así somos en Veredillas FM. De {currentArtist} saltamos a {nextArtist} con {nextTitle}.",
    "¡Qué bien suena {currentArtist}! Pues espera a escuchar el drop de {nextArtist} en {nextTitle}. ¡Brutal!",
    "La esencia de la radio está aquí. Tras {currentArtist}, recibimos a {nextArtist} con {nextTitle}.",
    "¡Qué energía nos regala {currentArtist}! Ideal para disfrutar ahora de {nextArtist} y su {nextTitle}.",
    "¡Vaya temazo de {currentArtist}! Pero lo que viene ahora con {nextArtist} es de otro planeta: {nextTitle}.",
    "Sigue conectado. Tras el éxito de {currentArtist}, llega {nextArtist} para romper los esquemas con {nextTitle}.",
    "¡Qué maravilla {currentArtist}! La magia continúa con {nextArtist} y su propuesta para hoy: {nextTitle}.",
    "¡Pura dinamita! {currentArtist} nos ha dejado con la boca abierta. {nextArtist} viene a cerrarla con {nextTitle}.",
    "¡Qué voz, qué talento el de {currentArtist}! La calidad sigue con {nextArtist} en su tema {nextTitle}.",
    "¡Vaya ritmo nos ha metido {currentArtist}! {nextArtist} lo lleva a otro nivel con {nextTitle}.",
    "¡Espectacular {currentTitle}! {userName}, no te muevas porque {nextArtist} entra con {nextTitle} ahora mismo.",
    "La radio que no descansa te trae a {currentArtist} y a continuación a {nextArtist} con {nextTitle}.",
    "¡Qué hit se ha marcado {currentArtist}! Pero el próximo de {nextArtist}, {nextTitle}, va por el mismo camino.",
    "¡Menuda joya musical! Gracias {currentArtist}. Ahora es el turno de {nextArtist} y su {nextTitle}.",
    "¡Qué bien entra {currentArtist}! Pues agárrate que {nextArtist} viene con su {nextTitle} a tope.",
    "Veredillas FM, siempre un paso por delante. Tras {currentArtist}, llega lo nuevo de {nextArtist}: {nextTitle}.",
    "¡Qué fuerza tiene {currentArtist}! La potencia sigue con {nextArtist} dándolo todo en {nextTitle}.",
    "¡Vaya clásico! {currentArtist} nunca falla. Renovamos el sonido con {nextArtist} y {nextTitle}.",
    "¡Insuperable {currentArtist}! O casi, porque {nextArtist} viene a por todas con {nextTitle}.",
    "¡Qué bien lo pasamos! Tras {currentArtist}, la fiesta sigue con {nextArtist} y {nextTitle}.",
    "¡Menudo groove! {currentArtist} nos ha puesto a bailar. {nextArtist} nos mantiene en la pista con {nextTitle}.",
    "¡Fantástico {currentArtist}! {userName}, prepárate para la descarga de {nextArtist} con {nextTitle}.",
    "¡Qué sonido! {currentArtist} dejando el listón muy alto. ¿Podrá {nextArtist} con su {nextTitle}? ¡Escucha!",
    "¡Inolvidable! {currentTitle} sonando ahora. Y para no perder la costumbre, aquí está {nextArtist} con {nextTitle}.",
    "¡Vaya vibra! {currentArtist} nos ha contagiado. {nextArtist} nos lleva aún más lejos con {nextTitle}.",
    "¡Qué grande {currentArtist}! La leyenda sigue viva en Veredillas FM con {nextArtist} y {nextTitle}.",
    "¡Menudo temazo! Gracias {currentArtist}. Ahora, prepárate para la locura de {nextArtist} con {nextTitle}.",
    "¡Simplemente brutal! {currentArtist} ha destrozado los esquemas. {nextArtist} viene a reconstruirlos con {nextTitle}.",
    "Veredillas FM, tu radio, tu música. De {currentArtist} pasamos sin frenos a {nextArtist} y {nextTitle}.",
    "¡Qué flow! {currentArtist} tiene ese toque. Y {nextArtist} no se queda atrás con su {nextTitle}.",
    "¡Menudo descubrimiento! {currentArtist} nos ha sorprendido. Los éxitos siguen con {nextArtist} y {nextTitle}.",
    "¡Vaya subida! {currentArtist} nos ha puesto en órbita. {nextArtist} nos mantiene allí con {nextTitle}.",
    "¡Qué fuerza! {currentTitle} rugiendo en los altavoces. {nextArtist} toma el relevo con {nextTitle}.",
    "¡No paramos! De {currentArtist} a {nextArtist} con {nextTitle}. ¡Veredillas FM en vena!",
    "¡Qué bien suena {currentArtist}! Y mejor va a sonar {nextArtist} con {nextTitle}. ¡Ya verás!",
    "¡Menuda pieza! {currentArtist} aportando calidad. Lo nuevo de {nextArtist} también es canela fina: {nextTitle}.",
    "¡Vaya energía! {currentArtist} nos ha puesto a tope. Transmitimos ese mood a {nextArtist} y su {nextTitle}.",
    "¡Qué talento! {currentArtist} demostrando por qué es el mejor. El genio sigue con {nextArtist} y {nextTitle}.",
    "¡Atención, familia! Si {currentArtist} os ha gustado, lo que viene de {nextArtist} en {nextTitle} os va a encantar.",
    "¡Qué hit! {currentArtist} marcando tendencia. La moda sigue en Veredillas FM con {nextArtist} y {nextTitle}.",
    "¡Vaya ritmo! {currentArtist} nos ha puesto a mil. {nextArtist} viene a rematar la faena con {nextTitle}.",
    "¡Qué temazo, por favor! Gracias {currentArtist}. {userName}, disfruta ahora de {nextArtist} y {nextTitle}.",
    "¡Simplemente épico! {currentArtist} haciendo historia. {nextArtist} escribe el siguiente capítulo con {nextTitle}.",
    "Veredillas FM, la señal que te mueve. Tras {currentArtist}, recibimos a {nextArtist} con {nextTitle}.",
    "¡Qué bien entra este tema de {currentArtist}! Y la cosa mejora con {nextArtist} y su {nextTitle}.",
    "¡Menudo subidón nos ha dado {currentArtist}! Para que no baje, {nextArtist} nos regala {nextTitle}.",
    "¡Brutal {currentArtist}! La antena echa chispas. {nextArtist} viene con el extintor musical: {nextTitle}.",
    "¡Qué clase! {currentArtist} poniendo el punto de distinción. La elegancia sigue con {nextArtist} y {nextTitle}.",
    "¡Vaya pepinazo! {currentArtist} ha roto los moldes. {nextArtist} trae moldes nuevos en {nextTitle}.",
    "¡Qué bien nos lo pasamos! Gracias {currentArtist}. La diversión continúa con {nextArtist} y {nextTitle}.",
    "¡Menudo groove! {currentArtist} nos ha metido en el bolsillo. {nextArtist} nos saca a bailar con {nextTitle}.",
    "¡Fantástico! Así suena {currentTitle}. Pero prepárate, porque {nextArtist} ya está aquí con {nextTitle}.",
    "¡Qué sonido más potente! Gracias {currentArtist}. {nextArtist} toma el mando con {nextTitle}.",
    "¡Inolvidable! {currentArtist} siempre en nuestro corazón. Y ahora, {nextArtist} en nuestra antena con {nextTitle}."
];

export const fallbackPhrases = [
    "¡Vaya temazo acabamos de escuchar de {currentArtist}! Seguimos con la mejor selección musical aquí en Veredillas efe eme.",
    "Ese fue {currentArtist} rompiéndola. No te despegues, {userName}, porque seguimos con mucha más música buena.",
    "Estás en Veredillas efe eme. Después de este increíble tema de {currentArtist}, seguimos con más éxitos imparables.",
    "Pura buena vibra con {currentTitle}. Quédate con nosotros que la música no se detiene ni un segundo.",
    "¡Eso estuvo genial! Despedimos a {currentArtist} y seguimos adelante. Ya sabes que en Veredillas efe eme suenan los mejores.",
    "¡Qué nivel el de {currentArtist}! Sigue en sintonía, {userName}, porque la próxima canción te va a volar la cabeza.",
    "¡Fantástico! {currentArtist} nunca falla. Seguimos explorando el universo musical en Veredillas FM.",
    "¡Menudo viaje nos ha dado {currentArtist}! Prepárate para lo que viene, porque la radio no descansa.",
    "Veredillas FM, donde los éxitos viven. Tras {currentArtist}, la fiesta continúa.",
    "¡Esa es la actitud! Gracias a {currentArtist} por este momento. Seguimos conectados a la mejor señal.",
    "¿Te ha gustado? Pues no te vayas, que lo que tenemos preparado en Veredillas FM es harina de otro costal.",
    "¡Vaya directo de {currentArtist}! La calidad es nuestra marca y aquí seguimos demostrándolo.",
    "¡Qué bien suena la radio hoy! Gracias {currentArtist}. Seguimos dándote lo que pides.",
    "Veredillas efe eme, tu radio amiga. Después de {currentArtist}, más música, más ritmo, más vida.",
    "¡Simplemente espectacular {currentArtist}! Sintonizas la frecuencia que marca el paso.",
    "¡Vaya hit nos ha regalado {currentArtist}! Pero la recámara de Veredillas FM está llena de balas como esta.",
    "¡No pares el ritmo! {currentArtist} nos ha dejado con la energía por las nubes.",
    "¡Qué clase! {currentArtist} siempre aportando ese toque especial. Seguimos en la onda.",
    "¿Quién dijo miedo? {currentArtist} nos ha puesto a prueba y hemos superado el nivel. ¡Seguimos!",
    "Veredillas FM, la banda sonora de tu vida. Gracias {currentArtist} por este temazo.",
    "¡Vaya exhibición de talento de {currentArtist}! La radio se hace grande con temas así.",
    "¡Qué energía! {currentArtist} nos ha dejado las pilas cargadas para todo el día.",
    "Sigue en Veredillas efe eme, donde la música no conoce fronteras. Gracias {currentArtist}.",
    "¡Menudo temazo para recordar! {currentArtist} poniéndonos nostálgicos pero con ritmo.",
    "¡Brutal! {currentArtist} ha destrozado los altavoces. Vamos a por el siguiente asalto.",
    "¡Qué elegancia la de {currentArtist}! Seguimos con nuestra cuidada selección musical.",
    "¡Vaya descubrimiento! Si te ha gustado {currentArtist}, quédate porque hay mucho más.",
    "¡Pura dinamita {currentArtist}! La antena está que arde en Veredillas efe eme.",
    "¡Qué bien nos cuida {currentArtist}! Pero nosotros también te cuidamos con lo que viene.",
    "Veredillas FM, siempre a tu lado con la mejor música. Gracias {currentArtist}.",
    "¡Vaya hit! {currentArtist} demostrando por qué está en la cima. Seguimos adelante.",
    "¡Qué bien suena Veredillas FM! Gracias {currentArtist} por este momento.",
    "No te desconectes. Tras {currentArtist}, la música sigue siendo la protagonista.",
    "¡Simplemente increíble! {currentArtist} nos ha dejado sin palabras. ¡A por más!",
    "Veredillas efe eme, tu radio favorita. Gracias {currentArtist} por el temazo.",
    "¡Vaya ritmo! {currentArtist} nos ha puesto a bailar a todos. ¡Seguimos!",
    "¡Qué temazo! {currentArtist} nunca decepciona en nuestra antena.",
    "Veredillas FM, la casa de los éxitos. Tras {currentArtist}, más madera.",
    "¡Brutal! {currentArtist} ha puesto el listón altísimo. ¿Quién lo superará?",
    "¡Qué energía positiva! Gracias {currentArtist}. Seguimos con buen rollo.",
    "Veredillas efe eme, siempre contigo. Tras {currentArtist}, más música de calidad.",
    "¡Vaya temazo para la historia! Gracias {currentArtist} por compartirlo aquí.",
    "¡Espectacular! {currentArtist} nos ha hecho vibrar. ¡No te vayas!",
    "Veredillas FM, el sonido que te gusta. Gracias {currentArtist} por estar ahí.",
    "¡Qué bien sienta este tema de {currentArtist}! Seguimos en directo.",
    "¡Menudo pepinazo! {currentArtist} ha reventado los índices de audiencia.",
    "Veredillas efe eme, sintonía pura. Tras {currentArtist}, seguimos a tope.",
    "¡Qué voz! {currentArtist} nos ha emocionado. La música sigue en tu radio.",
    "¡Vaya hitazo! {currentArtist} es sinónimo de éxito en Veredillas FM.",
    "Veredillas FM, donde nace la música. Gracias {currentArtist} por el aporte."
];
