/**
 * POST /api/auth/canariaseducacion/register-pending
 *
 * Called SERVER-TO-SERVER by the Google Apps Script bridge via UrlFetchApp.
 * No browser sandbox restrictions apply — this is a direct HTTPS server call.
 *
 * Body (JSON): { authId, email, token }
 *   - authId: UUID generated by the main tab, passed to Apps Script via URL param
 *   - email:  the @canariaseducacion.es address from Session.getActiveUser()
 *   - token:  HMAC-SHA256(email, CANARIAS_EDUCACION_BRIDGE_SECRET) computed by Apps Script
 */

import type { APIRoute } from 'astro';
import mongoose from 'mongoose';
import { PendingCanariasAuth } from '../../../../models/PendingCanariasAuth';
import { isValidToken, isAllowedDomain } from '../../../../lib/canariaseducacion-auth';

export const prerender = false;

async function connectDB() {
  if (mongoose.connection.readyState === 1) return;
  const uri = import.meta.env.MONGODB_URI;
  if (!uri) throw new Error('MONGODB_URI not set');
  await mongoose.connect(uri);
}

export const POST: APIRoute = async ({ request }) => {
  const fail = (msg: string, status = 400) =>
    new Response(JSON.stringify({ ok: false, error: msg }), {
      status,
      headers: { 'Content-Type': 'application/json' },
    });

  let body: { authId?: string; email?: string; token?: string };
  try {
    body = await request.json();
  } catch {
    return fail('Invalid JSON body');
  }

  const { authId, email: rawEmail, token } = body;

  if (!authId || !rawEmail || !token) return fail('Missing fields');

  const email = rawEmail.trim().toLowerCase();
  const secret = import.meta.env.CANARIAS_EDUCACION_BRIDGE_SECRET;

  if (!secret) return fail('Server misconfiguration', 500);
  if (!isAllowedDomain(email)) return fail('Domain not allowed');
  if (!isValidToken(rawEmail, token, secret)) {
    console.error('[CanariasAuth] register-pending: invalid token for', email);
    return fail('Invalid token', 403);
  }

  try {
    await connectDB();
    // Upsert so re-tries from Apps Script don't create duplicates
    await PendingCanariasAuth.findOneAndUpdate(
      { authId },
      { authId, email },
      { upsert: true, new: true }
    );
    return new Response(JSON.stringify({ ok: true }), {
      status: 200,
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (err) {
    console.error('[CanariasAuth] register-pending error:', err);
    return fail('Database error', 500);
  }
};
